PS1='\[\033[01;32m\]\u@DOCKER_CONT(\h)\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
export PATH=$PATH:/developer_bin
export CMAKE_EXPORT_COMPILE_COMMANDS=ON

alias ls='ls --color=auto'
alias grep='grep --color=auto'
