version: '3.7'

services:
    webrend_dev_unstable:
        cap_add:
            - SYS_ADMIN
        build:
            context: ./debian_based
            args:
              IMAGE: debian:unstable-20211011
              PROJECT_DIRECTORY: webrend
        restart: always
        volumes:
            - ..:/webrend
            - /home/${SUDO_USER:-$LOGNAME}/.gitconfig:/home/cxx-developer/.gitconfig
            - /home/${SUDO_USER:-$LOGNAME}/.ssh:/home/cxx-developer/.ssh
        stdin_open: true
        tty: true
