option(ENABLE_CCACHE "Enable ccache" ON)
if(ENABLE_CCACHE)
    find_program(CCACHE ccache)
    if(CCACHE)
        set(CMAKE_CXX_COMPILER_LAUNCHER ${CCACHE})
    else()
	message(WARNING "Couldn't find ccache")
    endif()
endif()
